// @ts-check
import { defineConfig } from "astro/config";
import starlight from "@astrojs/starlight";
import { fileURLToPath } from "node:url";
import brand from "./src/brand/brand.config.json" with { type: "json" };

/**
 * Generic brand hub engine.
 *
 * Nothing brand-specific is written here — it all comes from the synced
 * src/brand/brand.config.json. Adding a section to a brand repo's config puts it in the
 * sidebar; the engine doesn't need to know it exists.
 */

/** Sections become sidebar entries, in the order the brand lists them.

    A section is one of two things:

      { "dir": "company", "label": "Company" }        a folder, autogenerated
      { "link": "using-with-ai", "label": "…" }       one standalone page

    The second exists because autogeneration only walks folders. A brand's root-level
    pages — the homepage and its neighbours — could otherwise never reach the sidebar, so
    a page like "using with AI" was reachable only from a link on the homepage.

    Starlight 0.39+ requires the autogenerate config to sit inside a group's items array
    rather than alongside its label. */
const sidebar = brand.sections.map((section) =>
  section.dir
    ? { label: section.label, items: [{ autogenerate: { directory: section.dir } }] }
    : { label: section.label, link: `/${section.link.replace(/^\/+|\/+$/g, "")}/` }
);

const fontHref = brand.font?.google
  ? `https://fonts.googleapis.com/css2?family=${brand.font.google.replace(/ /g, "+")}&display=swap`
  : null;

export default defineConfig({
  site: brand.site,
  vite: {
    resolve: {
      // Brand content is synced to varying depths under src/content/docs, so injected
      // component imports use a stable alias rather than a relative path.
      // fileURLToPath, not URL.pathname — the latter percent-encodes spaces in the path.
      alias: { "@components": fileURLToPath(new URL("./src/components", import.meta.url)) },
    },
  },
  integrations: [
    starlight({
      title: brand.siteTitle,
      description: `The ${brand.name} brand hub — guidelines, assets and templates.`,
      logo: {
        light: brand.logo.light.replace("/assets", "./public/assets"),
        dark: brand.logo.dark.replace("/assets", "./public/assets"),
        replacesTitle: false,
      },
      favicon: brand.logo.favicon,
      customCss: ["./src/styles/tokens.css", "./src/styles/custom.css"],
      head: fontHref
        ? [
            { tag: "link", attrs: { rel: "preconnect", href: "https://fonts.googleapis.com" } },
            { tag: "link", attrs: { rel: "preconnect", href: "https://fonts.gstatic.com", crossorigin: true } },
            { tag: "link", attrs: { rel: "stylesheet", href: fontHref } },
          ]
        : [],
      components: {
        // Adds a "download as Markdown" link alongside Starlight's own footer.
        Footer: "./src/components/Footer.astro",
      },
      lastUpdated: true,
      sidebar,
      pagination: true,
      credits: false,
    }),
  ],
});
